### ISSUE TITLE
Default file name is missing

### ISSUE THREAD

**Issue by droople** [arunelias/table-download#1]
Hi There,
It's a great add-on.
Only one thing I notice, the default file name is ".xls", if I choose open with excel, it won't be open. Could you please change the name to sheet.xls ?

Cheers

**Comment by arunelias** [comment]
Hi,
Thanks for reporting this issue. 
File name was not assigned as the browser was assigning a random filename to it earlier. This does not occur in latest version of Firefox.

**Comment by arunelias** [comment]
Resolved in the version 1.2
